import fs from "node:fs/promises";
import path from "node:path";
import { loadConfig, resolveMemoryDir } from "./config";

export const AI_CONTEXT_MANAGED_START = "<!-- devmemory:managed:start -->";
export const AI_CONTEXT_MANAGED_END = "<!-- devmemory:managed:end -->";

const MANAGED_NOTE =
  "<!-- This block is regenerated by the DevMemory AI VS Code extension. Anything OUTSIDE these markers is preserved on every export. -->";

const PLACEHOLDER_PHRASES = [
  "Replace these placeholders",
  "Document the main modules",
  "Summarize what this project is"
];

const MANAGED_BLOCK_PATTERN =
  /<!--\s*devmemory:managed:start\s*-->[\s\S]*?<!--\s*devmemory:managed:end\s*-->/;

export interface AIContextTarget {
  id: "claude" | "agents" | "copilot" | "cursorrules";
  filePath: string;
  label: string;
}

export const AI_CONTEXT_TARGETS: readonly AIContextTarget[] = [
  {
    id: "claude",
    filePath: "CLAUDE.md",
    label: "CLAUDE.md (Anthropic Claude Code)"
  },
  {
    id: "agents",
    filePath: "AGENTS.md",
    label: "AGENTS.md (Codex / agentic conventions)"
  },
  {
    id: "copilot",
    filePath: path.posix.join(".github", "copilot-instructions.md"),
    label: ".github/copilot-instructions.md (GitHub Copilot)"
  },
  {
    id: "cursorrules",
    filePath: ".cursorrules",
    label: ".cursorrules (Cursor, legacy)"
  }
];

export interface SectionSnapshot {
  title: string;
  body: string;
}

interface SectionFile {
  title: string;
  relativePath: string;
}

const SECTION_FILES: SectionFile[] = [
  { title: "Project Summary", relativePath: "project-summary.md" },
  { title: "Architecture", relativePath: "architecture.md" },
  { title: "Current State", relativePath: "current-state.md" },
  { title: "Next Actions", relativePath: path.join("tasks", "next-actions.md") }
];

export type AIContextMemoryStatus =
  | { kind: "ok"; sections: SectionSnapshot[] }
  | { kind: "missing"; missing: string[] }
  | { kind: "placeholders"; files: string[] };

export async function inspectAIContextMemory(rootDir: string): Promise<AIContextMemoryStatus> {
  const config = await loadConfig(rootDir);
  const memoryDir = resolveMemoryDir(rootDir, config);

  const missing: string[] = [];
  const placeholderFiles: string[] = [];
  const sections: SectionSnapshot[] = [];

  for (const file of SECTION_FILES) {
    const absolute = path.join(memoryDir, file.relativePath);
    let raw: string;
    try {
      raw = await fs.readFile(absolute, "utf8");
    } catch {
      missing.push(file.relativePath);
      continue;
    }
    if (PLACEHOLDER_PHRASES.some((phrase) => raw.includes(phrase))) {
      placeholderFiles.push(file.relativePath);
      continue;
    }
    sections.push({ title: file.title, body: extractBody(raw) });
  }

  if (missing.length > 0) {
    return { kind: "missing", missing };
  }
  if (placeholderFiles.length > 0) {
    return { kind: "placeholders", files: placeholderFiles };
  }
  return { kind: "ok", sections };
}

function extractBody(raw: string): string {
  const lines = raw.split(/\r?\n/);
  let i = 0;
  while (i < lines.length) {
    const trimmed = lines[i].trim();
    if (trimmed.length === 0 || (trimmed.startsWith("<!--") && trimmed.endsWith("-->"))) {
      i++;
      continue;
    }
    break;
  }
  if (i < lines.length && /^#\s/.test(lines[i])) {
    i++;
    while (i < lines.length && lines[i].trim() === "") {
      i++;
    }
  }
  return lines.slice(i).join("\n").trimEnd();
}

export function composeAIContextBlock(
  sections: SectionSnapshot[],
  generatedAt: Date = new Date()
): string {
  const lines: string[] = [
    AI_CONTEXT_MANAGED_START,
    MANAGED_NOTE,
    `<!-- generated: ${generatedAt.toISOString()} -->`,
    "",
    "# Project Context (managed by DevMemory AI)",
    ""
  ];
  for (const section of sections) {
    const body = section.body.trim().length > 0 ? section.body.trim() : "_No content yet._";
    lines.push(`## ${section.title}`, "", body, "");
  }
  lines.push(AI_CONTEXT_MANAGED_END);
  return lines.join("\n");
}

export interface SpliceOutcome {
  content: string;
  action: "created" | "updated" | "appended";
}

export function spliceManagedBlock(existing: string | null, managedBlock: string): SpliceOutcome {
  if (existing === null || existing.length === 0) {
    return { content: `${managedBlock}\n`, action: "created" };
  }
  if (MANAGED_BLOCK_PATTERN.test(existing)) {
    return {
      content: existing.replace(MANAGED_BLOCK_PATTERN, managedBlock),
      action: "updated"
    };
  }
  const sep = existing.endsWith("\n") ? "" : "\n";
  return { content: `${existing}${sep}\n${managedBlock}\n`, action: "appended" };
}

export interface ExportAIContextOptions {
  targets: ReadonlyArray<AIContextTarget>;
  generatedAt?: Date;
}

export interface AIContextWriteResult {
  target: AIContextTarget;
  filePath: string;
  action: "created" | "updated" | "appended";
}

export async function exportAIContextFiles(
  rootDir: string,
  options: ExportAIContextOptions
): Promise<AIContextWriteResult[]> {
  if (options.targets.length === 0) {
    return [];
  }

  const rootAbsolute = path.resolve(rootDir);
  const resolvedTargets = options.targets.map((target) => ({
    target,
    absolute: resolveTargetPath(rootAbsolute, target)
  }));

  const inspection = await inspectAIContextMemory(rootDir);
  if (inspection.kind === "missing") {
    throw new Error(
      `DevMemory memory is incomplete. Missing: ${inspection.missing.join(", ")}. Run "Set Up Memory" and then "Teach DevMemory About This Project" first.`
    );
  }
  if (inspection.kind === "placeholders") {
    throw new Error(
      `DevMemory memory still contains placeholder content (${inspection.files.join(", ")}). Run "Teach DevMemory About This Project" so the AI replaces it before exporting.`
    );
  }

  const block = composeAIContextBlock(inspection.sections, options.generatedAt);
  const results: AIContextWriteResult[] = [];

  for (const { target, absolute } of resolvedTargets) {
    let existing: string | null = null;
    try {
      existing = await fs.readFile(absolute, "utf8");
    } catch {
      existing = null;
    }
    const outcome = spliceManagedBlock(existing, block);
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, outcome.content, "utf8");
    results.push({ target, filePath: absolute, action: outcome.action });
  }

  return results;
}

function resolveTargetPath(rootAbsolute: string, target: AIContextTarget): string {
  const absolute = path.resolve(rootAbsolute, target.filePath);
  const relative = path.relative(rootAbsolute, absolute);
  if (relative === "" || relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`AI context target must stay inside the workspace: ${target.filePath}`);
  }
  return absolute;
}
