import type { MemoryConfig } from "./types";

export const DEFAULT_MEMORY_DIR = ".ai-memory";

export const DEFAULT_INCLUDE_PATTERNS = [
  "README.md",
  "README.*",
  "LICENSE",
  "LICENSE.*",
  "CHANGELOG.md",
  "docs/**/*",
  ".github/workflows/**/*"
];

export const DEFAULT_EXCLUDE_PATTERNS = [
  ".ai-memory/**",
  "**/.ai-memory/**",
  ".git/**",
  "**/.git/**",
  ".env",
  ".env.*",
  "**/.env",
  "**/.env.*",
  "*.pem",
  "**/*.pem",
  "*.key",
  "**/*.key",
  "*.crt",
  "**/*.crt",
  "*.p12",
  "**/*.p12",
  "*.pfx",
  "**/*.pfx",
  "id_rsa",
  "id_ed25519",
  "**/id_rsa",
  "**/id_ed25519",
  "secrets.*",
  "**/secrets.*",
  "credentials.*",
  "**/credentials.*",
  "*.sqlite",
  "**/*.sqlite",
  "*.sqlite3",
  "**/*.sqlite3",
  "*.db",
  "**/*.db",
  ".npmrc",
  "**/.npmrc",
  ".yarnrc",
  "**/.yarnrc",
  ".pypirc",
  "**/.pypirc",
  ".netrc",
  "**/.netrc",
  ".aws/**",
  "**/.aws/**",
  ".ssh/**",
  "**/.ssh/**",
  ".kube/**",
  "**/.kube/**",
  "kubeconfig",
  "**/kubeconfig",
  "wp-config.php",
  "**/wp-config.php",
  "config/master.key",
  "**/config/master.key",
  "config/credentials.yml.enc",
  "**/config/credentials.yml.enc",
  "terraform.tfstate",
  "**/terraform.tfstate",
  "terraform.tfstate.backup",
  "**/terraform.tfstate.backup",
  "*.tfvars",
  "**/*.tfvars",
  "*.keystore",
  "**/*.keystore",
  "google-services.json",
  "**/google-services.json",
  "GoogleService-Info.plist",
  "**/GoogleService-Info.plist",
  "serviceAccount*.json",
  "**/serviceAccount*.json",
  "*firebase-adminsdk*.json",
  "**/*firebase-adminsdk*.json",
  "node_modules/**",
  "**/node_modules/**",
  "vendor/**",
  "**/vendor/**",
  ".venv/**",
  "**/.venv/**",
  "venv/**",
  "**/venv/**",
  "__pycache__/**",
  "**/__pycache__/**",
  ".pytest_cache/**",
  "**/.pytest_cache/**",
  ".mypy_cache/**",
  "**/.mypy_cache/**",
  "instance/**",
  "**/instance/**",
  "uploads/**",
  "**/uploads/**",
  "dist/**",
  "**/dist/**",
  "build/**",
  "**/build/**",
  "out/**",
  "**/out/**",
  "target/**",
  "**/target/**",
  "bin/**",
  "**/bin/**",
  "obj/**",
  "**/obj/**",
  "coverage/**",
  "**/coverage/**",
  ".next/**",
  "**/.next/**",
  ".nuxt/**",
  "**/.nuxt/**",
  ".turbo/**",
  "**/.turbo/**",
  ".cache/**",
  "**/.cache/**",
  ".gradle/**",
  "**/.gradle/**",
  ".idea/**",
  "**/.idea/**",
  ".dart_tool/**",
  "**/.dart_tool/**",
  ".build/**",
  "**/.build/**",
  "DerivedData/**",
  "**/DerivedData/**",
  "Pods/**",
  "**/Pods/**"
];

export const DEFAULT_CONFIG: MemoryConfig = {
  version: 1,
  memoryDir: DEFAULT_MEMORY_DIR,
  mode: "local",
  include: DEFAULT_INCLUDE_PATTERNS,
  exclude: DEFAULT_EXCLUDE_PATTERNS,
  maxFileBytes: 200_000,
  auditFileReads: true,
  llmProvider: "manual"
};
