import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { DEFAULT_MEMORY_DIR } from "./defaults";
import {
  applyBootstrapMemory,
  applySessionUpdate,
  generateBootstrapPrompt,
  generateSessionEndPrompt,
  initializeMemory,
  parseSessionUpdatePreview,
  quarantineFlaggedSessions,
  runMemoryHealthCheck
} from "./memory";
import { MANAGED_MARKER } from "./templates";

describe("initializeMemory managed-markdown policy", () => {
  let tempDir: string;
  let memoryDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "devmemory-mem-"));
    memoryDir = path.join(tempDir, DEFAULT_MEMORY_DIR);

    await fs.writeFile(path.join(tempDir, "app.py"), "print('hi')\n", "utf8");
    await fs.writeFile(path.join(tempDir, "requirements.txt"), "flask==3.0\n", "utf8");
    await fs.mkdir(path.join(tempDir, ".venv", "lib"), { recursive: true });
    await fs.writeFile(path.join(tempDir, ".venv", "lib", "secret.py"), "TOKEN='x'\n", "utf8");
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("overwrites a stale project-summary.md generated by an older version", async () => {
    await fs.mkdir(memoryDir, { recursive: true });
    const summaryPath = path.join(memoryDir, "project-summary.md");
    await fs.writeFile(
      summaryPath,
      [
        "# Project Summary",
        "",
        "## Detected Project Signals",
        "",
        "- Tracked files: 2",
        "- Skipped files: 3227",
        "- Package manifest detected: no",
        "",
        "## Important Files",
        "",
        "- .venv/lib/python3.12/site-packages/flask/sansio/README.md",
        ""
      ].join("\n"),
      "utf8"
    );

    await initializeMemory(tempDir);

    const updated = await fs.readFile(summaryPath, "utf8");
    expect(updated.startsWith(MANAGED_MARKER)).toBe(true);
    expect(updated).not.toContain("Package manifest detected");
    expect(updated).not.toContain(".venv");
    expect(updated).toContain("Detected technologies: Python");
  });

  it("preserves a manually edited project-summary.md without the managed marker", async () => {
    await fs.mkdir(memoryDir, { recursive: true });
    const summaryPath = path.join(memoryDir, "project-summary.md");
    const handcrafted = [
      "# My Project",
      "",
      "## Why It Exists",
      "",
      "I wrote this section by hand and want it preserved.",
      ""
    ].join("\n");
    await fs.writeFile(summaryPath, handcrafted, "utf8");

    await initializeMemory(tempDir);

    const after = await fs.readFile(summaryPath, "utf8");
    expect(after).toBe(handcrafted);
    expect(after).not.toContain(MANAGED_MARKER);
  });

  it("rewrites managed files when only the marker is present", async () => {
    await fs.mkdir(memoryDir, { recursive: true });
    const commandsPath = path.join(memoryDir, "commands.md");
    await fs.writeFile(commandsPath, `${MANAGED_MARKER}\n\n# Commands\n\nold body\n`, "utf8");

    await initializeMemory(tempDir);

    const updated = await fs.readFile(commandsPath, "utf8");
    expect(updated.startsWith(MANAGED_MARKER)).toBe(true);
    expect(updated).toContain("pip install -r requirements.txt");
    expect(updated).not.toContain("old body");
  });

  it("generateBootstrapPrompt writes a stack-aware prompt to .ai-memory/prompts", async () => {
    const result = await generateBootstrapPrompt(tempDir);

    const expectedPath = path.join(memoryDir, "prompts", "bootstrap-memory-prompt.md");
    expect(result.promptPath).toBe(expectedPath);

    const content = await fs.readFile(expectedPath, "utf8");
    expect(content).toContain("Detected technologies: Python");
    expect(content).toContain("- app.py");
    expect(content).toContain("## PROJECT_SUMMARY");
  });

  it("applyBootstrapMemory writes the four managed files when all sections are present", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "Some preface the AI added (should be ignored).",
      "",
      "## PROJECT_SUMMARY",
      "ErgonoMaster is a Flask app for ergonomic assessments.",
      "",
      "## ARCHITECTURE",
      "- Flask routes in app.py",
      "- Templates under templates/",
      "",
      "## CURRENT_STATE",
      "- Working: /assessment endpoint",
      "- In progress: PDF export",
      "",
      "## NEXT_ACTIONS",
      "- Add /history page",
      "- Cover assessment scoring with tests",
      ""
    ].join("\n");

    const result = await applyBootstrapMemory(tempDir, markdown);

    expect(result.filesWritten).toHaveLength(4);

    const summary = await fs.readFile(path.join(memoryDir, "project-summary.md"), "utf8");
    expect(summary.startsWith(MANAGED_MARKER)).toBe(true);
    expect(summary).toContain("# Project Summary");
    expect(summary).toContain("ErgonoMaster is a Flask app");

    const architecture = await fs.readFile(path.join(memoryDir, "architecture.md"), "utf8");
    expect(architecture).toContain("# Architecture");
    expect(architecture).toContain("- Flask routes in app.py");

    const currentState = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    expect(currentState).toContain("# Current State");
    expect(currentState).toContain("Working: /assessment endpoint");

    const nextActions = await fs.readFile(
      path.join(memoryDir, "tasks", "next-actions.md"),
      "utf8"
    );
    expect(nextActions).toContain("# Next Actions");
    expect(nextActions).toContain("- Add /history page");
  });

  it("applyBootstrapMemory accepts title-case section headings", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## Project Summary",
      "Title-case summary body.",
      "",
      "## Architecture",
      "- Module A",
      "",
      "## Current State",
      "- Working: feature X",
      "",
      "## Next Actions",
      "- Ship feature Y",
      ""
    ].join("\n");

    const result = await applyBootstrapMemory(tempDir, markdown);

    expect(result.filesWritten).toHaveLength(4);
    const summary = await fs.readFile(path.join(memoryDir, "project-summary.md"), "utf8");
    expect(summary).toContain("Title-case summary body.");
    const arch = await fs.readFile(path.join(memoryDir, "architecture.md"), "utf8");
    expect(arch).toContain("- Module A");
    const next = await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8");
    expect(next).toContain("- Ship feature Y");
  });

  it("applyBootstrapMemory still accepts the uppercase underscored headings", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## PROJECT_SUMMARY",
      "Uppercase summary.",
      "",
      "## ARCHITECTURE",
      "- Module B",
      "",
      "## CURRENT_STATE",
      "- Working",
      "",
      "## NEXT_ACTIONS",
      "- Done",
      ""
    ].join("\n");

    const result = await applyBootstrapMemory(tempDir, markdown);
    expect(result.filesWritten).toHaveLength(4);
    const summary = await fs.readFile(path.join(memoryDir, "project-summary.md"), "utf8");
    expect(summary).toContain("Uppercase summary.");
  });

  it("applyBootstrapMemory throws and writes nothing when a section is missing", async () => {
    await initializeMemory(tempDir);

    const summaryPath = path.join(memoryDir, "project-summary.md");
    const architecturePath = path.join(memoryDir, "architecture.md");
    const currentStatePath = path.join(memoryDir, "current-state.md");
    const nextActionsPath = path.join(memoryDir, "tasks", "next-actions.md");

    const before = {
      summary: await fs.readFile(summaryPath, "utf8"),
      architecture: await fs.readFile(architecturePath, "utf8"),
      currentState: await fs.readFile(currentStatePath, "utf8"),
      nextActions: await fs.readFile(nextActionsPath, "utf8")
    };

    const incomplete = [
      "## PROJECT_SUMMARY",
      "Just a summary, no other sections.",
      ""
    ].join("\n");

    await expect(applyBootstrapMemory(tempDir, incomplete)).rejects.toThrow(/missing required sections/i);

    expect(await fs.readFile(summaryPath, "utf8")).toBe(before.summary);
    expect(await fs.readFile(architecturePath, "utf8")).toBe(before.architecture);
    expect(await fs.readFile(currentStatePath, "utf8")).toBe(before.currentState);
    expect(await fs.readFile(nextActionsPath, "utf8")).toBe(before.nextActions);
  });

  it("generateSessionEndPrompt writes prompts/session-end-prompt.md", async () => {
    const result = await generateSessionEndPrompt(tempDir);

    const expectedPath = path.join(memoryDir, "prompts", "session-end-prompt.md");
    expect(result.promptPath).toBe(expectedPath);

    const content = await fs.readFile(expectedPath, "utf8");
    expect(content).toContain("## SESSION_SUMMARY");
    expect(content).toContain("## NEXT_ACTIONS");
  });

  it("applySessionUpdate creates a session log and refreshes current-state and next-actions", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## SESSION_SUMMARY",
      "Wired the new pricing endpoint.",
      "",
      "## CHANGES_MADE",
      "- Added /pricing route",
      "",
      "## FILES_TOUCHED",
      "- app.py",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "- pytest",
      "",
      "## CURRENT_STATE",
      "- Working: /pricing endpoint",
      "",
      "## NEXT_ACTIONS",
      "- Add /pricing tests",
      ""
    ].join("\n");

    const result = await applySessionUpdate(tempDir, markdown);

    const sessionEntry = result.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    expect(sessionEntry).toBeDefined();
    expect(sessionEntry!.endsWith("-session.md")).toBe(true);

    const sessionContent = await fs.readFile(sessionEntry!, "utf8");
    expect(sessionContent.startsWith("<!-- devmemory:managed -->")).toBe(true);
    expect(sessionContent).toContain("## Session Summary");
    expect(sessionContent).toContain("Wired the new pricing endpoint.");
    expect(sessionContent).toContain("## Files Touched");
    expect(sessionContent).toContain("- app.py");

    const current = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    expect(current).toContain("# Current State");
    expect(current).toContain("Working: /pricing endpoint");

    const next = await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8");
    expect(next).toContain("# Next Actions");
    expect(next).toContain("- Add /pricing tests");

    const decisionsExists = await fs
      .access(path.join(memoryDir, "decisions", "decisions.md"))
      .then(() => true)
      .catch(() => false);
    expect(decisionsExists).toBe(false);

    const bugsExists = await fs
      .access(path.join(memoryDir, "issues", "bugs-and-fixes.md"))
      .then(() => true)
      .catch(() => false);
    expect(bugsExists).toBe(false);
  });

  it("applySessionUpdate appends decisions and bugs when those sections are non-None", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## SESSION_SUMMARY",
      "Refactored auth module.",
      "",
      "## CHANGES_MADE",
      "- Extracted token verification helper",
      "",
      "## FILES_TOUCHED",
      "- src/auth.py",
      "",
      "## DECISIONS",
      "- Use PyJWT instead of authlib",
      "",
      "## BUGS_FIXED",
      "- Token refresh raced with logout. Cause: missing lock around refresh state.",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "- Working: refresh tokens",
      "",
      "## NEXT_ACTIONS",
      "- Audit other consumers of authlib",
      ""
    ].join("\n");

    await applySessionUpdate(tempDir, markdown);

    const decisions = await fs.readFile(path.join(memoryDir, "decisions", "decisions.md"), "utf8");
    expect(decisions.startsWith("<!-- devmemory:managed -->")).toBe(true);
    expect(decisions).toContain("# Decisions");
    expect(decisions).toContain("- Use PyJWT instead of authlib");

    const bugs = await fs.readFile(path.join(memoryDir, "issues", "bugs-and-fixes.md"), "utf8");
    expect(bugs.startsWith("<!-- devmemory:managed -->")).toBe(true);
    expect(bugs).toContain("# Bugs and Fixes");
    expect(bugs).toContain("Token refresh raced with logout");

    // Second call appends rather than overwrites.
    const followUp = markdown.replace("- Use PyJWT instead of authlib", "- Adopt rotating refresh tokens");
    await applySessionUpdate(tempDir, followUp);
    const decisionsAfter = await fs.readFile(path.join(memoryDir, "decisions", "decisions.md"), "utf8");
    expect(decisionsAfter).toContain("- Use PyJWT instead of authlib");
    expect(decisionsAfter).toContain("- Adopt rotating refresh tokens");
  });

  it("applySessionUpdate accepts bare headings without ## prefix", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "SESSION_SUMMARY",
      "Implemented onboarding step.",
      "",
      "CHANGES_MADE",
      "- Added onboarding wizard",
      "",
      "FILES_TOUCHED",
      "- src/onboarding.ts",
      "",
      "DECISIONS",
      "- Use react-hook-form",
      "",
      "BUGS_FIXED",
      "None",
      "",
      "COMMANDS_RUN",
      "- npm test",
      "",
      "CURRENT_STATE",
      "- Working: onboarding wizard MVP",
      "",
      "NEXT_ACTIONS",
      "- Add analytics events",
      ""
    ].join("\n");

    const result = await applySessionUpdate(tempDir, markdown);

    const sessionEntry = result.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    expect(sessionEntry).toBeDefined();
    const sessionContent = await fs.readFile(sessionEntry!, "utf8");
    expect(sessionContent).toContain("Implemented onboarding step.");
    expect(sessionContent).toContain("- src/onboarding.ts");

    const current = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    expect(current).toContain("- Working: onboarding wizard MVP");

    const next = await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8");
    expect(next).toContain("- Add analytics events");

    const decisions = await fs.readFile(path.join(memoryDir, "decisions", "decisions.md"), "utf8");
    expect(decisions).toContain("- Use react-hook-form");
  });

  it("applySessionUpdate still accepts ## prefixed headings", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## SESSION_SUMMARY",
      "Hash-prefixed summary.",
      "",
      "## CURRENT_STATE",
      "- Working: hashed flow",
      "",
      "## NEXT_ACTIONS",
      "- Iterate",
      ""
    ].join("\n");

    const result = await applySessionUpdate(tempDir, markdown);
    expect(result.filesWritten.length).toBeGreaterThanOrEqual(3);
    const current = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    expect(current).toContain("- Working: hashed flow");
  });

  it("applySessionUpdate writes a DevMemory Warnings section when warnings are passed", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## SESSION_SUMMARY",
      "Did some work.",
      "",
      "## CURRENT_STATE",
      "- Working: thing",
      "",
      "## NEXT_ACTIONS",
      "- Continue",
      ""
    ].join("\n");

    const result = await applySessionUpdate(tempDir, markdown, {
      warnings: [
        "Files Touched lists paths that do not exist: src/ghost.ts.",
        "Commands Run lists a destructive command: rm -rf."
      ]
    });

    const sessionEntry = result.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    expect(sessionEntry).toBeDefined();
    const sessionContent = await fs.readFile(sessionEntry!, "utf8");

    expect(sessionContent).toContain("## DevMemory Warnings");
    expect(sessionContent).toContain("- Files Touched lists paths that do not exist: src/ghost.ts.");
    expect(sessionContent).toContain("- Commands Run lists a destructive command: rm -rf.");

    const warningsIndex = sessionContent.indexOf("## DevMemory Warnings");
    const summaryIndex = sessionContent.indexOf("## Session Summary");
    expect(warningsIndex).toBeGreaterThan(0);
    expect(summaryIndex).toBeGreaterThan(warningsIndex);

    const current = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    expect(current).not.toContain("DevMemory Warnings");
    expect(current).not.toContain("rm -rf");

    const next = await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8");
    expect(next).not.toContain("DevMemory Warnings");
  });

  it("applySessionUpdate omits the DevMemory Warnings section when no warnings are provided", async () => {
    await initializeMemory(tempDir);

    const markdown = [
      "## SESSION_SUMMARY",
      "Clean session.",
      "",
      "## CURRENT_STATE",
      "ok",
      "",
      "## NEXT_ACTIONS",
      "next",
      ""
    ].join("\n");

    const noOptions = await applySessionUpdate(tempDir, markdown);
    const noOptSession = noOptions.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    const noOptContent = await fs.readFile(noOptSession!, "utf8");
    expect(noOptContent).not.toContain("DevMemory Warnings");

    const emptyArray = await applySessionUpdate(tempDir, markdown, { warnings: [] });
    const emptySession = emptyArray.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    const emptyContent = await fs.readFile(emptySession!, "utf8");
    expect(emptyContent).not.toContain("DevMemory Warnings");

    const blankOnly = await applySessionUpdate(tempDir, markdown, { warnings: ["   "] });
    const blankSession = blankOnly.filesWritten.find((p) => p.includes(`${path.sep}sessions${path.sep}`));
    const blankContent = await fs.readFile(blankSession!, "utf8");
    expect(blankContent).not.toContain("DevMemory Warnings");
  });

  it("applySessionUpdate fails atomically when CURRENT_STATE or NEXT_ACTIONS is missing", async () => {
    await initializeMemory(tempDir);

    const currentBefore = await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8");
    const nextBefore = await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8");
    const sessionsBefore = await fs.readdir(path.join(memoryDir, "sessions"));

    const markdown = [
      "## SESSION_SUMMARY",
      "Did some work.",
      "",
      "## CHANGES_MADE",
      "- Stuff",
      "",
      "## NEXT_ACTIONS",
      "- More stuff",
      ""
    ].join("\n");

    await expect(applySessionUpdate(tempDir, markdown)).rejects.toThrow(
      /missing required sections.*CURRENT_STATE/
    );

    expect(await fs.readFile(path.join(memoryDir, "current-state.md"), "utf8")).toBe(currentBefore);
    expect(await fs.readFile(path.join(memoryDir, "tasks", "next-actions.md"), "utf8")).toBe(nextBefore);
    expect(await fs.readdir(path.join(memoryDir, "sessions"))).toEqual(sessionsBefore);
  });

  it("parseSessionUpdatePreview flags simulated/fake content", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "Esta é uma SIMULAÇÃO da sessão para teste.",
      "",
      "## CURRENT_STATE",
      "- Working: stuff",
      "",
      "## NEXT_ACTIONS",
      "- Real work",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.missingRequired).toEqual([]);
    expect(preview.warnings.some((w) => /simulated|fictitious/i.test(w))).toBe(true);
    expect(preview.warnings.some((w) => /SIMULAÇÃO/i.test(w))).toBe(true);
  });

  it("parseSessionUpdatePreview also catches FAKE markers", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "FAKE summary used as a placeholder.",
      "",
      "## CURRENT_STATE",
      "ok",
      "",
      "## NEXT_ACTIONS",
      "next",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);
    expect(preview.warnings.length).toBeGreaterThan(0);
    expect(preview.warnings[0].toLowerCase()).toContain("fake");
  });

  it("parseSessionUpdatePreview flags missing files in FILES_TOUCHED", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "Did real work.",
      "",
      "## FILES_TOUCHED",
      "- app.py",
      "- src/does-not-exist.ts",
      "",
      "## CURRENT_STATE",
      "ok",
      "",
      "## NEXT_ACTIONS",
      "next",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown, tempDir);

    const filesWarning = preview.warnings.find((w) => w.toLowerCase().includes("files touched"));
    expect(filesWarning).toBeDefined();
    expect(filesWarning).toContain("src/does-not-exist.ts");
    expect(filesWarning).not.toContain("app.py");
  });

  it("parseSessionUpdatePreview flags rm -rf in COMMANDS_RUN", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "Cleanup.",
      "",
      "## COMMANDS_RUN",
      "- rm -rf node_modules",
      "",
      "## CURRENT_STATE",
      "clean",
      "",
      "## NEXT_ACTIONS",
      "reinstall",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);
    expect(preview.warnings.some((w) => w.includes("rm -rf"))).toBe(true);
  });

  it("parseSessionUpdatePreview reports missingRequired when CURRENT_STATE is absent", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "Did things.",
      "",
      "## NEXT_ACTIONS",
      "- Continue",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);
    expect(preview.missingRequired).toContain("CURRENT_STATE");
    expect(preview.missingRequired).not.toContain("SESSION_SUMMARY");
    expect(preview.missingRequired).not.toContain("NEXT_ACTIONS");
  });

  it("parseSessionUpdatePreview warns when every section is empty or None", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "None",
      "",
      "## NEXT_ACTIONS",
      "None",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview warns when CURRENT_STATE only contains generic 'no changes' phrases", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "None",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "- No project changes were made",
      "- No work is currently in progress",
      "- Known issues: None",
      "",
      "## NEXT_ACTIONS",
      "None",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview does not warn when CURRENT_STATE has useful content", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "None",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "- Working: /pricing endpoint is live in staging",
      "",
      "## NEXT_ACTIONS",
      "None",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).not.toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview warns on a realistic empty AI response with bulleted None values", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "- None",
      "",
      "## FILES_TOUCHED",
      "* None",
      "",
      "## DECISIONS",
      "• None",
      "",
      "## BUGS_FIXED",
      "- None",
      "",
      "## COMMANDS_RUN",
      "- None",
      "",
      "## CURRENT_STATE",
      "- No project changes were made in this session.",
      "- No work is currently in progress from this session.",
      "- No known issues were identified in this session.",
      "",
      "## NEXT_ACTIONS",
      "- None",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview does not warn when a section mixes a None bullet with useful content", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "None",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "None",
      "",
      "## NEXT_ACTIONS",
      "- None",
      "- Add pricing tests",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).not.toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview treats the long generic CURRENT_STATE variants as effectively empty", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "None",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "- No project changes were made in this session",
      "- No work is currently in progress from this session",
      "",
      "## NEXT_ACTIONS",
      "None",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview does not warn when NEXT_ACTIONS has useful content", async () => {
    const markdown = [
      "## SESSION_SUMMARY",
      "None",
      "",
      "## CHANGES_MADE",
      "None",
      "",
      "## FILES_TOUCHED",
      "None",
      "",
      "## DECISIONS",
      "None",
      "",
      "## BUGS_FIXED",
      "None",
      "",
      "## COMMANDS_RUN",
      "None",
      "",
      "## CURRENT_STATE",
      "None",
      "",
      "## NEXT_ACTIONS",
      "- Add /pricing tests covering tax edge cases",
      ""
    ].join("\n");

    const preview = await parseSessionUpdatePreview(markdown);

    expect(preview.warnings).not.toContain("Session summary appears empty or non-informative.");
  });

  it("parseSessionUpdatePreview never writes files", async () => {
    const memoryDirBefore = await fs.readdir(tempDir);
    const memoryDirExistsBefore = memoryDirBefore.includes(".ai-memory");

    const markdown = [
      "## SESSION_SUMMARY",
      "Some summary.",
      "",
      "## CURRENT_STATE",
      "ok",
      "",
      "## NEXT_ACTIONS",
      "next",
      ""
    ].join("\n");

    await parseSessionUpdatePreview(markdown, tempDir);

    const memoryDirAfter = await fs.readdir(tempDir);
    const memoryDirExistsAfter = memoryDirAfter.includes(".ai-memory");
    expect(memoryDirExistsAfter).toBe(memoryDirExistsBefore);
  });

  it("runMemoryHealthCheck reports healthy after initialize + apply bootstrap", async () => {
    await initializeMemory(tempDir);

    const bootstrap = [
      "## PROJECT_SUMMARY",
      "Real summary, no placeholders here.",
      "",
      "## ARCHITECTURE",
      "- Main module: app.py",
      "",
      "## CURRENT_STATE",
      "- Working: things",
      "",
      "## NEXT_ACTIONS",
      "- Continue building.",
      ""
    ].join("\n");
    await applyBootstrapMemory(tempDir, bootstrap);

    const { result, reportPath } = await runMemoryHealthCheck(tempDir);

    expect(result.status).toBe("healthy");
    expect(result.warnings).toEqual([]);
    expect(reportPath).toBe(path.join(memoryDir, "health-check.md"));

    const report = await fs.readFile(reportPath, "utf8");
    expect(report).toContain("# Memory Health Check");
    expect(report).toContain("Status: healthy");
  });

  it("runMemoryHealthCheck flags placeholders left from initial template", async () => {
    await initializeMemory(tempDir);

    const { result } = await runMemoryHealthCheck(tempDir);

    expect(result.status).toBe("needs-review");
    const placeholderCheck = result.checks.find((entry) => entry.id === "placeholders");
    expect(placeholderCheck?.status).toBe("warn");
    expect(result.warnings.some((w) => w.includes("placeholder text"))).toBe(true);
  });

  it("runMemoryHealthCheck flags sessions applied with DevMemory Warnings", async () => {
    await initializeMemory(tempDir);

    const cleanBootstrap = [
      "## PROJECT_SUMMARY",
      "Clean.",
      "## ARCHITECTURE",
      "Clean.",
      "## CURRENT_STATE",
      "ok",
      "## NEXT_ACTIONS",
      "next"
    ].join("\n");
    await applyBootstrapMemory(tempDir, cleanBootstrap);

    const sessionMarkdown = [
      "## SESSION_SUMMARY",
      "ok",
      "## CURRENT_STATE",
      "ok",
      "## NEXT_ACTIONS",
      "next"
    ].join("\n");
    await applySessionUpdate(tempDir, sessionMarkdown, {
      warnings: ["Files Touched lists paths that do not exist: src/ghost.ts."]
    });

    const { result } = await runMemoryHealthCheck(tempDir);

    expect(result.status).toBe("needs-review");
    const sessionCheck = result.checks.find((entry) => entry.id === "session-warnings");
    expect(sessionCheck?.status).toBe("warn");
    expect(result.warnings.some((w) => w.includes("Sessions applied with warnings"))).toBe(true);
  });

  it("runMemoryHealthCheck flags an empty manifest.files", async () => {
    await initializeMemory(tempDir);
    const cleanBootstrap = [
      "## PROJECT_SUMMARY",
      "Clean.",
      "## ARCHITECTURE",
      "Clean.",
      "## CURRENT_STATE",
      "ok",
      "## NEXT_ACTIONS",
      "next"
    ].join("\n");
    await applyBootstrapMemory(tempDir, cleanBootstrap);

    const manifestPath = path.join(memoryDir, "manifest.json");
    const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8"));
    manifest.files = [];
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), "utf8");

    const { result } = await runMemoryHealthCheck(tempDir);
    expect(result.status).toBe("needs-review");
    const manifestCheck = result.checks.find((entry) => entry.id === "manifest");
    expect(manifestCheck?.status).toBe("warn");
    expect(result.warnings.some((w) => /0 files/i.test(w))).toBe(true);
  });

  it("quarantineFlaggedSessions moves only sessions containing DevMemory Warnings", async () => {
    await initializeMemory(tempDir);

    const sessionsDir = path.join(memoryDir, "sessions");
    await fs.mkdir(sessionsDir, { recursive: true });

    const flaggedName = "2026-04-25-10-00-00-flagged.md";
    const cleanName = "2026-04-25-11-00-00-clean.md";

    await fs.writeFile(
      path.join(sessionsDir, flaggedName),
      [
        "<!-- devmemory:managed -->",
        "",
        "# Session 2026-04-25T10:00:00.000Z",
        "",
        "## DevMemory Warnings",
        "",
        "- Files Touched lists paths that do not exist: src/ghost.ts.",
        "",
        "## Session Summary",
        "",
        "Real-looking but flagged session.",
        ""
      ].join("\n"),
      "utf8"
    );

    await fs.writeFile(
      path.join(sessionsDir, cleanName),
      [
        "<!-- devmemory:managed -->",
        "",
        "# Session 2026-04-25T11:00:00.000Z",
        "",
        "## Session Summary",
        "",
        "Honest summary, no warnings here.",
        ""
      ].join("\n"),
      "utf8"
    );

    const outcome = await quarantineFlaggedSessions(tempDir);

    expect(outcome.movedFiles).toHaveLength(1);
    expect(outcome.movedFiles[0]).toContain(`${path.sep}quarantine${path.sep}sessions${path.sep}`);
    expect(outcome.movedFiles[0].endsWith(flaggedName)).toBe(true);

    const remainingSessions = await fs.readdir(sessionsDir);
    expect(remainingSessions).toContain(cleanName);
    expect(remainingSessions).not.toContain(flaggedName);

    const quarantinedListing = await fs.readdir(
      path.join(memoryDir, "quarantine", "sessions")
    );
    expect(quarantinedListing).toContain(flaggedName);

    const log = await fs.readFile(outcome.quarantineLogPath, "utf8");
    expect(log.startsWith("<!-- devmemory:managed -->")).toBe(true);
    expect(log).toContain("# Quarantine Log");
    expect(log).toContain("Reason: session log contained `## DevMemory Warnings`.");
    expect(log).toContain(flaggedName);

    const health = await fs.readFile(outcome.healthCheckPath, "utf8");
    expect(health).toContain("# Memory Health Check");
    expect(health).toContain("No session logs flagged with DevMemory Warnings.");
  });

  it("quarantineFlaggedSessions returns an empty list when no sessions are flagged", async () => {
    await initializeMemory(tempDir);

    const sessionsDir = path.join(memoryDir, "sessions");
    await fs.mkdir(sessionsDir, { recursive: true });
    const cleanName = "2026-04-25-12-00-00-clean.md";
    await fs.writeFile(
      path.join(sessionsDir, cleanName),
      "<!-- devmemory:managed -->\n\n# Session\n\n## Session Summary\n\nClean.\n",
      "utf8"
    );

    const outcome = await quarantineFlaggedSessions(tempDir);

    expect(outcome.movedFiles).toEqual([]);
    expect((await fs.readdir(sessionsDir)).sort()).toEqual([cleanName]);

    const quarantineDir = path.join(memoryDir, "quarantine", "sessions");
    const quarantineExists = await fs
      .access(quarantineDir)
      .then(() => true)
      .catch(() => false);
    expect(quarantineExists).toBe(false);

    const health = await fs.readFile(outcome.healthCheckPath, "utf8");
    expect(health).toContain("# Memory Health Check");
  });

  it("produces a Python resume-prompt.md that does not leak .venv paths", async () => {
    await initializeMemory(tempDir);

    const resumePromptPath = path.join(memoryDir, "prompts", "resume-prompt.md");
    const prompt = await fs.readFile(resumePromptPath, "utf8");

    expect(prompt).toContain("## Project Summary");
    expect(prompt).toContain("Detected technologies: Python");
    expect(prompt).not.toContain(MANAGED_MARKER);
    expect(prompt).not.toContain(".venv/");
    expect(prompt).not.toContain("site-packages");
    expect(prompt).toContain("pip install -r requirements.txt");

    const projectHeadingMatches = prompt.match(/^# Project Summary$/gm) ?? [];
    expect(projectHeadingMatches).toHaveLength(0);
  });
});
