import fs from "node:fs/promises";
import path from "node:path";
import * as vscode from "vscode";

const MANAGED_START = "// devmemory:managed:start";
const MANAGED_END = "// devmemory:managed:end";

/**
 * Writes/updates `.vscode/mcp.json` with a DevMemory server entry between managed
 * markers. Anything outside the markers is preserved on every export.
 *
 * Note: VS Code's mcp.json is JSON-with-comments. We use line-comment markers so
 * a strict parser still works.
 */
export async function writeMcpManifest(
  workspaceRoot: string,
  extensionUri: vscode.Uri
): Promise<{ filePath: string; action: "created" | "updated" | "appended" }> {
  const mcpDir = path.join(workspaceRoot, ".vscode");
  const filePath = path.join(mcpDir, "mcp.json");
  await fs.mkdir(mcpDir, { recursive: true });

  const serverScript = path.join(extensionUri.fsPath, "dist", "mcp-server.js");
  const serverEntry = renderServerEntry(serverScript, workspaceRoot);

  let existing: string | null = null;
  try {
    existing = await fs.readFile(filePath, "utf8");
  } catch (error) {
    if (!isMissing(error)) throw error;
  }

  if (existing === null || existing.trim().length === 0) {
    const initial = renderInitialMcpFile(serverEntry);
    await fs.writeFile(filePath, initial, "utf8");
    return { filePath, action: "created" };
  }

  if (existing.includes(MANAGED_START) && existing.includes(MANAGED_END)) {
    const updated = existing.replace(buildManagedRegex(), buildManagedBlock(serverEntry));
    await fs.writeFile(filePath, updated, "utf8");
    return { filePath, action: "updated" };
  }

  const block = buildManagedBlock(serverEntry);
  const sep = existing.endsWith("\n") ? "" : "\n";
  await fs.writeFile(filePath, `${existing}${sep}\n${block}\n`, "utf8");
  return { filePath, action: "appended" };
}

function renderServerEntry(serverScript: string, workspaceRoot: string): string {
  // Use forward slashes for cross-platform JSON friendliness.
  const safePath = serverScript.split(path.sep).join("/");
  const safeWorkspace = workspaceRoot.split(path.sep).join("/");
  return JSON.stringify(
    {
      type: "stdio",
      command: "node",
      args: [safePath],
      env: { DEVMEMORY_WORKSPACE: safeWorkspace }
    },
    null,
    2
  )
    .split("\n")
    .map((line) => `      ${line}`)
    .join("\n")
    .trim();
}

function buildManagedBlock(serverEntry: string): string {
  return [
    `${MANAGED_START}`,
    `// Generated by DevMemory AI VS Code extension. Re-run "Enable MCP Server" to refresh this block.`,
    `// Anything outside these markers is preserved on every export.`,
    `{`,
    `  "servers": {`,
    `    "devmemory": ${serverEntry}`,
    `  }`,
    `}`,
    `${MANAGED_END}`
  ].join("\n");
}

function renderInitialMcpFile(serverEntry: string): string {
  return [
    "// .vscode/mcp.json — discovered by Claude Code, Cursor, Cline, Continue and",
    "// any MCP-aware client. The block between devmemory:managed markers is",
    "// regenerated by the DevMemory AI extension. Anything outside is preserved.",
    "",
    buildManagedBlock(serverEntry),
    ""
  ].join("\n");
}

function buildManagedRegex(): RegExp {
  return new RegExp(`${escapeRegex(MANAGED_START)}[\\s\\S]*?${escapeRegex(MANAGED_END)}`);
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isMissing(error: unknown): boolean {
  return Boolean(
    error && typeof error === "object" && "code" in error && (error as { code?: string }).code === "ENOENT"
  );
}
